CREATE TABLE [dbo].[STUDENTS] (
    [Id]        INT           IDENTITY (1, 1) NOT NULL,
    [FIRSTNAME] NVARCHAR (50) NULL,
    [LASTNAME]  NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [CK_STUDENTS_FIRSTNAME] CHECK (len([FIRSTNAME])>=(4)),
    CONSTRAINT [CK_STUDENTS_LASTNAME] CHECK (len([LASTNAME])>=(4))
);

GO

CREATE NONCLUSTERED INDEX [IX_STUDENTS_LASTNAME]
    ON [dbo].[STUDENTS]([LASTNAME] ASC);
GO

CREATE TABLE [dbo].[TEACHERS](
	[Id] ΙΝΤ IDENTITY(1,1) NOT NULL,
	[FIRSTNAME] nvarchar(50) NULL,
	[LASTNAME] nvarchar(50) NULL,
PRIMARY KEY CLUSTERED ([Id] ASC),
CONSTRAINT [CK_TEACHERS_FIRSTNAME] CHECK (len([FIRSTNAME])>=(4)),
CONSTRAINT [CK_TEACHERS_LASTNAME] CHECK (len([LASTNAME])>=(4))
);
GO

CREATE NONCLUSTERED INDEX [IX_TEACHERS_LASTNAME] ON [dbo].[TEACHERS]
([LASTNAME] ASC);
GO
CREATE TABLE [dbo].[COURSES](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [nvarchar](250) NULL,
	[TEACHERID] [int] NULL,
PRIMARY KEY CLUSTERED ([Id] ASC),
CONSTRAINT [FK_COURSES_TEACHERID] FOREIGN KEY([TEACHERID]) 
	REFERENCES [dbo].[TEACHERS] ([Id]),
CONSTRAINT [CK_COURSES_DESCRIPTION] CHECK  (len([DESCRIPTION])>=(1))
);
GO

CREATE NONCLUSTERED INDEX [IX_COURSES_TEACHERID] ON [dbo].[COURSES]
([TEACHERID] ASC);
GO

CREATE TABLE [dbo].[STUDENTCOURSES](
	[STUDENTID] [int] NOT NULL,
	[COURSEID] [int] NOT NULL,
 CONSTRAINT [PK_STUDENTCOURSES] 
 PRIMARY KEY CLUSTERED ([STUDENTID] ASC, [COURSEID] ASC),
 CONSTRAINT [FK_STUDENTCOURSES_STUDENTID] FOREIGN KEY([STUDENTID])
	REFERENCES [dbo].[STUDENTS] ([Id]),
CONSTRAINT [FK_STUDENTCOURSES_COURSEID] FOREIGN KEY([COURSEID])
	REFERENCES [dbo].[COURSES] ([Id])
);
GO